vawt_1:
  controller:
    # Publish all joint states -----------------------------------
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 30
    position:
      # Position Controllers ---------------------------------------
      blade_1_position_controller:
        type: position_controllers/JointPositionController
        joint: blade_1_joint
        pid: {p: 10.0, i: 0.0, d: 1.0}

      blade_2_position_controller:
        type: position_controllers/JointPositionController
        joint: blade_2_joint
        pid: {p: 10.0, i: 0.0, d: 1.0}
